version: '3.8'

services:
  db-local:
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      timeout: 10s
      interval: 1s
      retries: 10
    ports: # для локального доступа
      - "127.0.0.1:5432:5432"
  web-local:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      db-local:
        condition: service_healthy
    env_file:
      - ./.env
    ports: # для локального доступа
#      - "5001"
#      - "5001:5001"
      - "5001:5000"
#  nginx:
#    image: nginx:1.21.3-alpine
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - web

volumes:
  postgres_data:
