version: '3.7'

services:
  postgis:
    build:
      context: .
      dockerfile: Dockerfile-postgres-client
    restart: always
    volumes:
      - postgis-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

volumes:
  postgis-data:
