version: '3.8'

volumes:
  postgres_data:

services:
  postgres-local:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.example
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      timeout: 10s
      interval: 1s
      retries: 10
    ports:
      - "5432:5432"
