version: '3.7'

volumes:
  postgis-data:

services:
  postgis:
    image: postgis/postgis:14-3.3-alpine
    container_name: db
    restart: always
    volumes:
      - postgis-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
