[tool.poetry]
name = "bot-delo-zhivet"
version = "0.1.0"
description = ""
authors = ["personage-hub <76659786+personage-hub@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "bot_delo_zhivet"}]

[tool.poetry.dependencies]
python = "^3.10"
pre-commit = "^2.20.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
