name: CI

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  lint-black:
    name: Black code formatter
    runs-on: gh-runner-1

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: formatter
        uses: psf/black@stable
        with:
          src: "."
          options: "--diff"

  lint-flake:
    name: Check PEP8 codestyle
    runs-on: gh-runner-1

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Verify that poetry.lock is consistent with pyproject.toml
        run: poetry lock --check

      - name: Install dependencies
        run: poetry install --with test

      - name: Test with flake8
        run: poetry run python -m flake8
